### ISSUE TITLE
Doubling switches after 1.0.3 update

### ISSUE THREAD

**Issue by childledj** [youridijk/homebridge-kaku-ics2000#5]
After update plugin to 1.0.3 version each device began to consist of two switches “bulb” and “switch” with only “switch” works to control kaku device.
![C44E622A-26BA-41C1-BBE9-552C0999B8CB](https://user-images.githubusercontent.com/38331621/184133675-3e253a07-cb2b-4c0a-8008-c02367f38961.png)

**Comment by youridijk** [comment]
I experienced the same issue when I updated the plugin. The issue is caused by the switch to switch as device type for devices that can only turn on or off. But homebridge as still the lightbulb in his cache. To solve the issue, [you need to empty your cache in the homebridge UI](https://github.com/oznu/homebridge-config-ui-x/issues/525). If that doesn't work, you need to remove your homebridge from your Home in the Home app, empty cache again and re-add your homebridge.

**Comment by childledj** [comment]
Yep! I have uninstall plugin, empty cached accessories, and after reboot reinstall plugin. Everything works flawlessly fine! And its great update. Thank you
